require File.expand_path(File.join(File.dirname(__FILE__), 'gen_img_helpers'))
include GenImgHelpers
require 'RMagick'
include Magick

# create img files for all possible combinations of trips
# also generate the .css file for using the generated images

# create list of all possible combinations of destinations
namespace :generate_colors do
  combinations = []
  
  desc "generate all possible combinations"
  task :generate_combinations => :environment do
    for i in (1..255).to_a.reverse
      combinations << number2letters(i)
    end
  end

  desc "generate image files"
  task :generate_images => :generate_combinations do
    for comb in combinations.sort
      gen_image(comb)
    end
  end

  desc "generate css text for destinations.css to colorize destinations "
  task :generate_css => :generate_combinations do
    css_path = RAILS_ROOT + '/public/stylesheets/destinations.css'
    f = File.open(css_path, 'w')
    f.write "/* this file auto generated by */\n"
    f.write "/* rake generate_colors:generate_css */\n"
    f.write "/*           or                      */\n"
    f.write "/* rake generate_colors:all */\n"
    f.write "/* DON'T EDIT THIS FILE.  Edits will be lost on next auto generation */\n"
    for comb in combinations.sort
      f.write <<-EOF
  .#{comb}{
     background: url(../images/#{comb}.jpg);
     #{comb.length > 1 ? 'background-repeat: no-repeat;' :''}
  }
  
      EOF
    end
  end

  desc "generate images and write css"
  task :all => [:generate_images, :generate_css]

end