desc "generate css text for vehicles.css to colorize vehicles "
  task :generate_vehicle_css => :environment do
    css_path = RAILS_ROOT + '/public/stylesheets/vehicles.css'
    f = File.open(css_path, 'w')
    f.write"/" + '*' * 80 + "/\n"
    f.write "/* this file auto generated by                                        */\n"
    f.write "/* rake generate_vehicle_css                                          */\n"
    f.write "/* DO NOT EDIT THIS FILE.  Edits will be lost on next auto generation */\n"
    f.write"/" + '*' * 80 + "/\n"
    for vehicle in Vehicle.all
      f.write <<-EOF
  .#{vehicle.name.gsub(' ', '-') + '-trip'}{
     background-color: #{vehicle.color}
  }

      EOF
    end
  end